language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

install:
  - pip install --src src --requirement .travis-$REQUIREMENTS-requirements.txt
  - pip install --src src --editable .
  - python src/babel/scripts/download_install_cldr.py

script: make test
