language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release
  - REQUIREMENTS=devel

install:
  - pip install --requirement .travis-$REQUIREMENTS-requirements.txt
  - pip install --editable git+https://github.com/mitsuhiko/babel.git#egg=Babel
  - pip install --editable .
  - python $VIRTUAL_ENV/src/babel/scripts/download_import_cldr.py
  - python src/babel/scripts/download_install_cldr.py

script: make test
